################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
Drivers/lvgl/lvgl/demos/benchmark/assets \
Drivers/lvgl/lvgl/demos/benchmark \
Drivers/lvgl/lvgl/demos/flex_layout \
Drivers/lvgl/lvgl/demos/keypad_encoder \
Drivers/lvgl/lvgl/demos \
Drivers/lvgl/lvgl/demos/multilang/assets/avatars \
Drivers/lvgl/lvgl/demos/multilang/assets/emojis \
Drivers/lvgl/lvgl/demos/multilang/assets/fonts \
Drivers/lvgl/lvgl/demos/multilang/assets \
Drivers/lvgl/lvgl/demos/multilang \
Drivers/lvgl/lvgl/demos/music/assets \
Drivers/lvgl/lvgl/demos/music \
Drivers/lvgl/lvgl/demos/render/assets \
Drivers/lvgl/lvgl/demos/render \
Drivers/lvgl/lvgl/demos/scroll \
Drivers/lvgl/lvgl/demos/stress \
Drivers/lvgl/lvgl/demos/transform/assets \
Drivers/lvgl/lvgl/demos/transform \
Drivers/lvgl/lvgl/demos/vector_graphic/assets \
Drivers/lvgl/lvgl/demos/vector_graphic \
Drivers/lvgl/lvgl/demos/widgets/assets \
Drivers/lvgl/lvgl/demos/widgets \
Drivers/lvgl/lvgl/env_support/pikascript \
Drivers/lvgl/lvgl/env_support/rt-thread \
Drivers/lvgl/lvgl/env_support/rt-thread/squareline \
Drivers/lvgl/lvgl/examples/anim \
Drivers/lvgl/lvgl/examples/assets \
Drivers/lvgl/lvgl/examples/assets/emoji \
Drivers/lvgl/lvgl/examples/event \
Drivers/lvgl/lvgl/examples/get_started \
Drivers/lvgl/lvgl/examples/layouts/flex \
Drivers/lvgl/lvgl/examples/layouts/grid \
Drivers/lvgl/lvgl/examples/libs/barcode \
Drivers/lvgl/lvgl/examples/libs/bmp \
Drivers/lvgl/lvgl/examples/libs/ffmpeg \
Drivers/lvgl/lvgl/examples/libs/freetype \
Drivers/lvgl/lvgl/examples/libs/gif \
Drivers/lvgl/lvgl/examples/libs/libjpeg_turbo \
Drivers/lvgl/lvgl/examples/libs/libpng \
Drivers/lvgl/lvgl/examples/libs/lodepng \
Drivers/lvgl/lvgl/examples/libs/qrcode \
Drivers/lvgl/lvgl/examples/libs/rlottie \
Drivers/lvgl/lvgl/examples/libs/tiny_ttf \
Drivers/lvgl/lvgl/examples/libs/tjpgd \
Drivers/lvgl/lvgl/examples/others/file_explorer \
Drivers/lvgl/lvgl/examples/others/fragment \
Drivers/lvgl/lvgl/examples/others/gridnav \
Drivers/lvgl/lvgl/examples/others/ime \
Drivers/lvgl/lvgl/examples/others/imgfont \
Drivers/lvgl/lvgl/examples/others/monkey \
Drivers/lvgl/lvgl/examples/others/observer \
Drivers/lvgl/lvgl/examples/others/snapshot \
Drivers/lvgl/lvgl/examples/porting \
Drivers/lvgl/lvgl/examples/porting/osal \
Drivers/lvgl/lvgl/examples/scroll \
Drivers/lvgl/lvgl/examples/styles \
Drivers/lvgl/lvgl/examples/widgets/animimg \
Drivers/lvgl/lvgl/examples/widgets/arc \
Drivers/lvgl/lvgl/examples/widgets/bar \
Drivers/lvgl/lvgl/examples/widgets/button \
Drivers/lvgl/lvgl/examples/widgets/buttonmatrix \
Drivers/lvgl/lvgl/examples/widgets/calendar \
Drivers/lvgl/lvgl/examples/widgets/canvas \
Drivers/lvgl/lvgl/examples/widgets/chart \
Drivers/lvgl/lvgl/examples/widgets/checkbox \
Drivers/lvgl/lvgl/examples/widgets/dropdown \
Drivers/lvgl/lvgl/examples/widgets/image \
Drivers/lvgl/lvgl/examples/widgets/imagebutton \
Drivers/lvgl/lvgl/examples/widgets/keyboard \
Drivers/lvgl/lvgl/examples/widgets/label \
Drivers/lvgl/lvgl/examples/widgets/led \
Drivers/lvgl/lvgl/examples/widgets/line \
Drivers/lvgl/lvgl/examples/widgets/list \
Drivers/lvgl/lvgl/examples/widgets/lottie \
Drivers/lvgl/lvgl/examples/widgets/menu \
Drivers/lvgl/lvgl/examples/widgets/msgbox \
Drivers/lvgl/lvgl/examples/widgets/obj \
Drivers/lvgl/lvgl/examples/widgets/roller \
Drivers/lvgl/lvgl/examples/widgets/scale \
Drivers/lvgl/lvgl/examples/widgets/slider \
Drivers/lvgl/lvgl/examples/widgets/span \
Drivers/lvgl/lvgl/examples/widgets/spinbox \
Drivers/lvgl/lvgl/examples/widgets/spinner \
Drivers/lvgl/lvgl/examples/widgets/switch \
Drivers/lvgl/lvgl/examples/widgets/table \
Drivers/lvgl/lvgl/examples/widgets/tabview \
Drivers/lvgl/lvgl/examples/widgets/textarea \
Drivers/lvgl/lvgl/examples/widgets/tileview \
Drivers/lvgl/lvgl/examples/widgets/win \
Drivers/lvgl/lvgl/src/core \
Drivers/lvgl/lvgl/src/display \
Drivers/lvgl/lvgl/src/draw \
Drivers/lvgl/lvgl/src/draw/nxp/pxp \
Drivers/lvgl/lvgl/src/draw/nxp/vglite \
Drivers/lvgl/lvgl/src/draw/renesas/dave2d \
Drivers/lvgl/lvgl/src/draw/sdl \
Drivers/lvgl/lvgl/src/draw/sw/blend/helium \
Drivers/lvgl/lvgl/src/draw/sw/blend \
Drivers/lvgl/lvgl/src/draw/sw/blend/neon \
Drivers/lvgl/lvgl/src/draw/sw \
Drivers/lvgl/lvgl/src/draw/vg_lite \
Drivers/lvgl/lvgl/src/drivers/display/drm \
Drivers/lvgl/lvgl/src/drivers/display/fb \
Drivers/lvgl/lvgl/src/drivers/display/ili9341 \
Drivers/lvgl/lvgl/src/drivers/display/lcd \
Drivers/lvgl/lvgl/src/drivers/display/renesas_glcdc \
Drivers/lvgl/lvgl/src/drivers/display/st7735 \
Drivers/lvgl/lvgl/src/drivers/display/st7789 \
Drivers/lvgl/lvgl/src/drivers/display/st7796 \
Drivers/lvgl/lvgl/src/drivers/evdev \
Drivers/lvgl/lvgl/src/drivers/glfw \
Drivers/lvgl/lvgl/src/drivers/libinput \
Drivers/lvgl/lvgl/src/drivers/nuttx \
Drivers/lvgl/lvgl/src/drivers/qnx \
Drivers/lvgl/lvgl/src/drivers/sdl \
Drivers/lvgl/lvgl/src/drivers/wayland \
Drivers/lvgl/lvgl/src/drivers/windows \
Drivers/lvgl/lvgl/src/drivers/x11 \
Drivers/lvgl/lvgl/src/font \
Drivers/lvgl/lvgl/src/indev \
Drivers/lvgl/lvgl/src/layouts/flex \
Drivers/lvgl/lvgl/src/layouts/grid \
Drivers/lvgl/lvgl/src/layouts \
Drivers/lvgl/lvgl/src/libs/barcode \
Drivers/lvgl/lvgl/src/libs/bin_decoder \
Drivers/lvgl/lvgl/src/libs/bmp \
Drivers/lvgl/lvgl/src/libs/ffmpeg \
Drivers/lvgl/lvgl/src/libs/freetype \
Drivers/lvgl/lvgl/src/libs/fsdrv \
Drivers/lvgl/lvgl/src/libs/gif \
Drivers/lvgl/lvgl/src/libs/libjpeg_turbo \
Drivers/lvgl/lvgl/src/libs/libpng \
Drivers/lvgl/lvgl/src/libs/lodepng \
Drivers/lvgl/lvgl/src/libs/lz4 \
Drivers/lvgl/lvgl/src/libs/qrcode \
Drivers/lvgl/lvgl/src/libs/rle \
Drivers/lvgl/lvgl/src/libs/rlottie \
Drivers/lvgl/lvgl/src/libs/tiny_ttf \
Drivers/lvgl/lvgl/src/libs/tjpgd \
Drivers/lvgl/lvgl/src \
Drivers/lvgl/lvgl/src/misc/cache \
Drivers/lvgl/lvgl/src/misc \
Drivers/lvgl/lvgl/src/osal \
Drivers/lvgl/lvgl/src/others/file_explorer \
Drivers/lvgl/lvgl/src/others/fragment \
Drivers/lvgl/lvgl/src/others/gridnav \
Drivers/lvgl/lvgl/src/others/ime \
Drivers/lvgl/lvgl/src/others/imgfont \
Drivers/lvgl/lvgl/src/others/monkey \
Drivers/lvgl/lvgl/src/others/observer \
Drivers/lvgl/lvgl/src/others/snapshot \
Drivers/lvgl/lvgl/src/others/sysmon \
Drivers/lvgl/lvgl/src/others/vg_lite_tvg \
Drivers/lvgl/lvgl/src/stdlib/builtin \
Drivers/lvgl/lvgl/src/stdlib/clib \
Drivers/lvgl/lvgl/src/stdlib \
Drivers/lvgl/lvgl/src/stdlib/micropython \
Drivers/lvgl/lvgl/src/stdlib/rtthread \
Drivers/lvgl/lvgl/src/themes/default \
Drivers/lvgl/lvgl/src/themes \
Drivers/lvgl/lvgl/src/themes/mono \
Drivers/lvgl/lvgl/src/themes/simple \
Drivers/lvgl/lvgl/src/tick \
Drivers/lvgl/lvgl/src/widgets/animimage \
Drivers/lvgl/lvgl/src/widgets/arc \
Drivers/lvgl/lvgl/src/widgets/bar \
Drivers/lvgl/lvgl/src/widgets/button \
Drivers/lvgl/lvgl/src/widgets/buttonmatrix \
Drivers/lvgl/lvgl/src/widgets/calendar \
Drivers/lvgl/lvgl/src/widgets/canvas \
Drivers/lvgl/lvgl/src/widgets/chart \
Drivers/lvgl/lvgl/src/widgets/checkbox \
Drivers/lvgl/lvgl/src/widgets/dropdown \
Drivers/lvgl/lvgl/src/widgets/image \
Drivers/lvgl/lvgl/src/widgets/imagebutton \
Drivers/lvgl/lvgl/src/widgets/keyboard \
Drivers/lvgl/lvgl/src/widgets/label \
Drivers/lvgl/lvgl/src/widgets/led \
Drivers/lvgl/lvgl/src/widgets/line \
Drivers/lvgl/lvgl/src/widgets/list \
Drivers/lvgl/lvgl/src/widgets/lottie \
Drivers/lvgl/lvgl/src/widgets/menu \
Drivers/lvgl/lvgl/src/widgets/msgbox \
Drivers/lvgl/lvgl/src/widgets/objx_templ \
Drivers/lvgl/lvgl/src/widgets/property \
Drivers/lvgl/lvgl/src/widgets/roller \
Drivers/lvgl/lvgl/src/widgets/scale \
Drivers/lvgl/lvgl/src/widgets/slider \
Drivers/lvgl/lvgl/src/widgets/span \
Drivers/lvgl/lvgl/src/widgets/spinbox \
Drivers/lvgl/lvgl/src/widgets/spinner \
Drivers/lvgl/lvgl/src/widgets/switch \
Drivers/lvgl/lvgl/src/widgets/table \
Drivers/lvgl/lvgl/src/widgets/tabview \
Drivers/lvgl/lvgl/src/widgets/textarea \
Drivers/lvgl/lvgl/src/widgets/tileview \
Drivers/lvgl/lvgl/src/widgets/win \
Drivers/lvgl/lvgl/tests/makefile \
Drivers/lvgl/lvgl/tests/makefile_uefi \
Drivers/lvgl/lvgl/tests/src \
Drivers/lvgl/lvgl/tests/src/test_assets \
Drivers/lvgl/lvgl/tests/src/test_cases \
Drivers/lvgl/lvgl/tests/src/test_cases/cache \
Drivers/lvgl/lvgl/tests/src/test_cases/draw \
Drivers/lvgl/lvgl/tests/src/test_cases/libs \
Drivers/lvgl/lvgl/tests/src/test_cases/widgets \
Drivers/lvgl/lvgl/tests/src/test_libs/rnd_unicodes \
Drivers/lvgl/lvgl/tests/src/test_libs/rnd_unicodes/rnd_unicodes/src \
Drivers/lvgl/lvgl/tests/test_images/stride_align1/LZ4 \
Drivers/lvgl/lvgl/tests/test_images/stride_align1/RLE \
Drivers/lvgl/lvgl/tests/test_images/stride_align1/UNCOMPRESSED \
Drivers/lvgl/lvgl/tests/test_images/stride_align64/LZ4 \
Drivers/lvgl/lvgl/tests/test_images/stride_align64/RLE \
Drivers/lvgl/lvgl/tests/test_images/stride_align64/UNCOMPRESSED \
Drivers/lvgl/lvgl/tests/unity \
Drivers/lvgl/ui/components \
Drivers/lvgl/ui/screens \
Drivers/lvgl/ui \

